### ISSUE TITLE
[JENKINS-74802] LDAP Authentication fails after upgrading to 2.479.1

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/ldap-plugin#600]
<p>Hi, I updated this morning from 2.462.3 to 2.479.1 and I can't log in anymore. I downgraded to version 2.462.3 and I can log in again. The command <b>journalctl -u jenkins -f</b> shows that the process fails due to the following exception:</p>

<p> </p>

<p><tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>: 2024-11-01 12:01:52.030+0000 <span class="error">&#91;id=109&#93;</span>        WARNING        h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID c378f0bd-e6c6-400d-9fb7-189a91528464</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>: java.lang.NoSuchMethodError: 'void org.springframework.util.Assert.isTrue(boolean)'</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils$CollectingAttributeValueCallbackHandler.handleAttributeValue(LdapUtils.java:343)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils.handleAttributeValue(LdapUtils.java:321)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils.iterateAttributeValues(LdapUtils.java:305)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils.collectAttributeValues(LdapUtils.java:287)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.DirContextAdapter.collectAttributeValuesAsList(DirContextAdapter.java:787)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.DirContextAdapter.getObjectAttributes(DirContextAdapter.java:776)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.SpringSecurityLdapTemplate.extractStringAttributeValues(SpringSecurityLdapTemplate.java:224)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.SpringSecurityLdapTemplate.lambda$searchForMultipleAttributeValues$2(SpringSecurityLdapTemplate.java:187)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.ContextMapperCallbackHandler.getObjectFromNameClassPair(ContextMapperCallbackHandler.java:69)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.CollectingNameClassPairCallbackHandler.handleNameClassPair(CollectingNameClassPairCallbackHandler.java:50)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:371)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:332)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:633)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:574)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForMultipleAttributeValues(SpringSecurityLdapTemplate.java:197)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.getGroupMembershipRoles(DefaultLdapAuthoritiesPopulator.java:223)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//hudson.security.LDAPSecurityRealm$AuthoritiesPopulatorImpl.getGroupMembershipRoles(LDAPSecurityRealm.java:1427)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.getGrantedAuthorities(DefaultLdapAuthoritiesPopulator.java:202)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//jenkins.security.plugins.ldap.FromGroupSearchLDAPGroupMembershipStrategy.getGrantedAuthorities(FromGroupSearchLDAPGroupMembershipStrategy.java:81)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//hudson.security.LDAPSecurityRealm$WrappedAuthoritiesPopulator.getGrantedAuthorities(LDAPSecurityRealm.java:1380)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.authentication.LdapAuthenticationProvider.loadUserAuthorities(LdapAuthenticationProvider.java:197)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:81)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)</tt><br/>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//hudson.security.LDAPSecurityRealm$LDAPAuthenticationManager.authenticate(LDAPSecurityRealm.java:992)</tt></p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ihr.png" title="ihr's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ihr">ihr</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-74802" target="_blank">LDAP Authentication fails after upgrading to 2.479.1</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>component(s)</b>: ldap-plugin
<li><b>label(s)</b>: jenkins, ldap, login
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2024-11-01T14:07:23+00:00
<li><b>votes</b>: 1
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-12-09
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Hi, I updated this morning from 2.462.3 to 2.479.1 and I can't log in anymore. I downgraded to version 2.462.3 and I can log in again. The command <b>journalctl -u jenkins -f</b> shows that the process fails due to the following exception:</p>

<p> </p>

<p><tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>: 2024-11-01 12:01:52.030+0000 <span class="error">&#91;id=109&#93;</span>        WARNING        h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID c378f0bd-e6c6-400d-9fb7-189a91528464</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>: java.lang.NoSuchMethodError: 'void org.springframework.util.Assert.isTrue(boolean)'</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils$CollectingAttributeValueCallbackHandler.handleAttributeValue(LdapUtils.java:343)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils.handleAttributeValue(LdapUtils.java:321)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils.iterateAttributeValues(LdapUtils.java:305)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.support.LdapUtils.collectAttributeValues(LdapUtils.java:287)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.DirContextAdapter.collectAttributeValuesAsList(DirContextAdapter.java:787)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.DirContextAdapter.getObjectAttributes(DirContextAdapter.java:776)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.SpringSecurityLdapTemplate.extractStringAttributeValues(SpringSecurityLdapTemplate.java:224)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.SpringSecurityLdapTemplate.lambda$searchForMultipleAttributeValues$2(SpringSecurityLdapTemplate.java:187)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.ContextMapperCallbackHandler.getObjectFromNameClassPair(ContextMapperCallbackHandler.java:69)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.CollectingNameClassPairCallbackHandler.handleNameClassPair(CollectingNameClassPairCallbackHandler.java:50)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:371)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:332)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:633)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.ldap.core.LdapTemplate.search(LdapTemplate.java:574)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.SpringSecurityLdapTemplate.searchForMultipleAttributeValues(SpringSecurityLdapTemplate.java:197)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.getGroupMembershipRoles(DefaultLdapAuthoritiesPopulator.java:223)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//hudson.security.LDAPSecurityRealm$AuthoritiesPopulatorImpl.getGroupMembershipRoles(LDAPSecurityRealm.java:1427)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.userdetails.DefaultLdapAuthoritiesPopulator.getGrantedAuthorities(DefaultLdapAuthoritiesPopulator.java:202)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//jenkins.security.plugins.ldap.FromGroupSearchLDAPGroupMembershipStrategy.getGrantedAuthorities(FromGroupSearchLDAPGroupMembershipStrategy.java:81)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//hudson.security.LDAPSecurityRealm$WrappedAuthoritiesPopulator.getGrantedAuthorities(LDAPSecurityRealm.java:1380)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.authentication.LdapAuthenticationProvider.loadUserAuthorities(LdapAuthenticationProvider.java:197)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:81)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)</tt>
<tt>Nov 01 13:01:52 jenkins jenkins<span class="error">&#91;31949&#93;</span>:         at PluginClassLoader for ldap//hudson.security.LDAPSecurityRealm$LDAPAuthenticationManager.authenticate(LDAPSecurityRealm.java:992)</tt></p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>2.479.1</code></li></ul>
